---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.9.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install: {}
  timeout: 10m0s
  interval: 10m0s
  values:
    fullnameOverride: postgresql
    postgresqlDatabase: ${HASS_POSTGRESQL_DATABASE}
    postgresqlUsername: ${HASS_POSTGRESQL_USERNAME}
    postgresqlPassword: ${HASS_POSTGRESQL_PASSWORD}
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 13.4.0
      pullPolicy: IfNotPresent
    persistence:
      enabled: true

