---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.13.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  install: {}
  timeout: 10m0s
  interval: 10m0s
  values:
    fullnameOverride: postgresql
    existingSecret: postgresql-secrets
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.1.0
      pullPolicy: IfNotPresent
    persistence:
      enabled: true

