---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      # registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      version: 10.9.1
  install: {}
  timeout: 10m0s
  interval: 10m0s
  values:
    fullnameOverride: postgresql
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 13.3.0
      pullPolicy: IfNotPresent
    persistence:
      enabled: true

