apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: home-assistant-code-server-secret
    namespace: flux-system
stringData:
    id_rsa: ENC[AES256_GCM,data:iA7z8EeSAN0PAObEJ614MP824rfJL/t4toveo0zR3Vung3H14W1CYaFjwW/oToL/0iYvNkYJ6uE0Ts0SGkPUJifxCLYgIc4q7b7Q+/091G+74g/m2zugUwafPKxZ7QKtY7vFQNk/aDx6mmeHJ/uLVSXMhbM0UrxnFLhFULwuP9gnNlMoTnIHEISFkTlfvp0GahmvCSOPeDudBnuz2wzJENlQ2UckM1rSTUzo7NDuYqBq3BBR8s48Z5arprfBf4pARtSD3zm6d4sRNQlJPcbV6UpubfMBVVo+09WWTSOpQi5NTkbSNkVUPA5H64bVMN4kfK7sOm/+u4c1r44nDa+A8J6yqgIoWGfZ/P1PnHfPFxj77yS8Yh/GIkFvYQNcp9V/f9QGvYwrSzIdzwMGA/Ugtdth899+CYpSrd9ZFE/+kYnXifdXZ9dKOxcpBaeN+21hQSgD1w22bmcPHFoIbHkAZwVB5oY2XWlp5FrKAe9sHfDkfQHEvJnp4jG3esvM1tlcrY5MgLo2IDnIiHoIDA==,iv:TNWozObKOxxR96BsoP8uvlt5FnUoMqib9aZ8WP5OT+I=,tag:UKW8PekLnIxAGRCTQD2Ftw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-25T19:55:38Z"
    mac: ENC[AES256_GCM,data:DegwY2U8oMNT596v7qrgAmbd2WCxy9Ty6x6t6lrvcT6OnUvsU4gjVjj6XuhFESc6G15+lAdFpgsYeR5U2jOd+dvRi68lpyknddgSb0Fq68sdMNo06+402j3V0zFDC6RPVZ8j1wpknf4xYksk6ouYwj3N3EoMtAcQ/s/onOIL4C4=,iv:Y/ekvJG/xWzgRncvUHzg0jWj9DJ8NDmK81My+NiYCHw=,tag:X/3GYEOjraWO/J1KMHDsFg==,type:str]
    pgp:
        - created_at: "2021-08-23T09:07:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0GTi4R/AiNSAQ//Y0ZP0N1fmcKRSWUxTfAlvPHoF4CqJATDPamcauKvMxZn
            tMyOcKU9jXpf/OcnajGuixf33i5g7P1afwp4TD7zJ1VSjCKfKlYlIKY5wOXZXqXV
            EtrAdL/NGwrkv2aMKqj1rj+6BNAg4pT0A3vRIXDvaJZ8jZF/UuzGQXq0yl8dCjRf
            WOOrrLAsAOCfNuWdRJP/WPNU6a1xmKd/4pBv0qrbZKUEwdJoijm4zqUXY9Gt6G0p
            DEHddwYPJNwVmwZw2gsd91wDNDzVTUuWhnUmKQc88kmDZFtHbqgTUp0iFouY78ax
            zXz983ZZ16u/k44LXUzRBXfzf1p2IPWsU3rE/uow9+n9atxx+zIO73A7goyhc0fT
            IQbkjSSorURy/F3mTBxRmo6qzcJauDHoXwvwL3jmL/PL3MmgoM6+Y7PeCM04sdtW
            aHJYumBjLP0aDv6ErilTLJgP4tpVPKkHKb8D/P1LnjNrOqY7tOYsbDTT4VQb36Q2
            LhChMN3hbrdWdxrhC8qUjK2uQSORYPrEsfut5y07b3cPQdfqqKRgCYi8F/nLxaDy
            h++RHRunh8Gzv5lYh9S9hGViUWnCB1JrfHReegLSbMvHegRZzESg/5pP2iznMbJx
            l9nyP60JMKDaxgNtkY5YFA3cfo2qCk6Yxb5NUoH8y9cD+5L3fowOOWoR5mORdBXS
            XgGk/U2pq7762FqhWtARZl3Vt6L24gbuB+UzxVvtUhHYgPLy8+0FkK0SnuDa30KO
            lN0YWG91x1C5GNVf1kFhmYMS3KxF7lalO8sCOwQ7txjKY1JQuUogddIgaSHfgg4=
            =8FJx
            -----END PGP MESSAGE-----
          fp: E60B7B08952B00CAFC82F154F079120C11682A03
        - created_at: "2021-08-23T09:07:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4bZl5U5v+PuAQ//bCcRAzl2mtPUBgCt89gns03YDIJ3VnGe/8/Jz2hugHPz
            Lf7YpljxSoMXl6bu1mDZk4tIyqq7wIZmnra4i42YPyBEXpLGpzsOTq0/ZysQqAS/
            a1qIUa3kxm7rAhVHhkr1/30eUA6TAH6Ulyp3uK5E/WdxBExmorplxyWs+QiKl2oN
            eef8cez852/SowoT71oGzoxY+mMR5+5OYuSE2z1p6B34Az4tXCsr/fBGtLP7W0SC
            taMve4pYcYAURAK6O05RcSKvF/4JPp9QgS/aHYMmPOMdaOCSUB8RDExyUXUVNjV1
            VYlmb+0DDkbynORyKYY88Y/srvSCb3FmFlT5BBXEvTsy6UV8tvZyeXPs9iqTpAKc
            okKpZr3G8gEAV6gyfF92JSsEOMvWue8oqMMQcUmlYvs4Ug2RXUCrKdt4wL52xAQU
            Hb3AQMjg1lE7AXxrizDPBRsD6Dt12hk9i7wpT+8kmtFse3xLT2v2P9Xo3jXnEjYH
            aEAcd6i2Zwz127K0vN/Ig06WAGip8eKDD5dyRJ3VjSjPp+rROlcv/LLT5zvuLI1Q
            Ci5tilC/PHOXL/WfRl5Ovap/9JTS4geT98GL5iG1E4Fc/B2jQz/HYKZOfdoRnwVy
            CCrthpARblpJAhW1k1BrrFCWcZGJGXdOo/fwSmDW6sJH5+7IGdd56NqyxTP/OPPS
            XgFhxeY3NCD+7pwg2gZynZjEyAwOfE2RH4JwMkG8nuyBw41SwRrBJXk03R3NbgV+
            R129WShWegOl2WtqIC2BbbHQMbsDzEGrSW82LDz9mC5OAe5eGg4n98fJjTLo1aE=
            =5/ow
            -----END PGP MESSAGE-----
          fp: FA5BAC037E2A4E178724D80AAB1216826FF58B88
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
