apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  timeout: 10m0s
  interval: 10m0s
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.8.4
    env:
      TZ: Europe/Amsterdam
#    envFrom:
#      - secretRef:
#          name: home-assistant-env

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ha.${SECRET_DOMAIN}"

    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
