apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 10.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  timeout: 10m0s
  interval: 10m0s
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.9.6
    envFrom:
     - secretRef:
         name: home-assistant-secrets

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "ha.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ha.${SECRET_DOMAIN}"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.11.1
        workingDir: "/config"
        git:
          deployKeySecret: home-assistant-code-server-secret
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            kubernetes.io/tls-acme: "true"
          hosts:
            - host: "ha-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "ha-vscode.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
