---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: flux-system
spec:
  interval: 5m
  releaseName: vernemq
  chart:
    spec:
      # renovate: registryUrl=https://vernemq.github.io/docker-vernemq
      chart: vernemq
      version: 1.6.7
      sourceRef:
        kind: HelmRepository
        name: vernemq-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vernemq/vernemq
      tag: 1.12.3-alpine
    replicaCount: 1
    service:
      type: ClusterIP
      externalIPs:
        - "${SVC_VERNEMQ_ADDRESS}"
      ws:
        enabled: true
        nodePort: 32080
      mqtt:
        enabled: true
        nodePort: 31883
    additionalEnv:
      - name: DOCKER_VERNEMQ_ACCEPT_EULA
        value: "yes"
      - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
        value: "on"
