---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tasmo-admin
  namespace: flux-system
spec:
  interval: 5m
  releaseName: tasmo-admin
  chart:
    spec:
      # renovate: registryUrl=https://charts.itstoni.com/
      chart: tasmo-admin
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: itstoni-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raymondmm/tasmoadmin
      pullPolicy: IfNotPresent
      tag: v1.7.0
    persistence:
      enabled: true
