---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  values:
    image:
      repository: ghcr.io/zwave-js/zwavejs2mqtt
      tag: 5.5.1
    env:
      TZ: "Europe/Amsterdam"
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
      usb:
        enabled: true
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        mountPath: /dev/serial/by-id/usb-0658_0200-if00
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
