# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:vMKahUZfk22dYJ937wIQudjWzyzyXM7tCNQ88QY9sMaJPD5ctuHDUg==,iv:0+mqlvQNX3Xg0SMtggpicJSjlAyMH329BpkGjHyj/LQ=,tag:OjlhsgxnEJcF55TVXWNQDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-10T22:18:09Z"
    mac: ENC[AES256_GCM,data:Dd1mQsneQlm5jLU0DSreiThXkARwlAht313QidbsDKRqoCs2WCS6eLdqPucRYnh/fIx/Rrx1AnTy9xxC333S0CZx2OHHpwmhsNoa6T3ZDHMuxMmDYdOMWgPAe09nsNJmHAPgdGu4/x7CbD+rvF8OhaRhdR9uzyUzZfuCWpCO9eI=,iv:/8jj51oxe943G1hAWxEU1Mg7/6b3CBKFpQOzSgfjJMc=,tag:4bD9e67ajt/rbTu94qUa+Q==,type:str]
    pgp:
        - created_at: "2021-08-10T22:18:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0GTi4R/AiNSAQ//VCi0gE6t47hFxjLkKSzFFIq9qcW66TRaTE2/IMdnceVn
            iQRubaTPvCCdTRLUdLeGS+J5JPfEuHiY9/cilxQ+clCLjQ6V/hNFJ5AdMz1lnKLa
            Hz2baH+ZtMoGzKq8Ijm7GT88gc49POU7iQh5lQ1rggxmBrL9XLx6iMK692wemcV4
            /+iLVP9n/M82irhLXgvC/xOUeGk8kP7jcsRRuGckuk47bgNEiQdeorNEbJpKK20T
            DrS/+Z+HnSj5DntyWuLjEcpx0ze9jsajQdvke6zQq+6UPmtqa5MY5X8D/piLqdHv
            ccoxBcdWM8XKy1V/kX7fG84kHjMtgimrJooXiEAIM1+P76/IZXmv5ci+SGHohhUm
            niLcEs+/2zWOar5MrISQmzEsFN/QeYwOVdqw6FaAHwjRA5LO2xYRnXoWcB/srrkZ
            vNpdbInhMGcyO6+zs3abnxKFLe5Sezy4UxoSRSLtFrAtwnyiyR6zS1fwPaY+8RV1
            C/xaEGCvNqDBMDAir5RcX2z1pr3UNS2yoMS2MRvkQlOVytjHi7mT7ih280q0XFrL
            8ccJjXDZopQt+yPnlvE/tN3BPB/i0cxn791MqUCgNXaQDc78d2f8cYWLiwx4M3H7
            XMG+ntqWjc/jWaNzNCjMpq3EAo23irWSJqn0mga9yEd+3T/1LFwzVIlntV2/eEvS
            XgH33U0lhEEv+WirQW2OCE45xw8wG5621E0eOkB3vSOoU+WULdmZDoqJazqShmWL
            NcoANXs4bAAp8J8f+K1UWGTlLORo+rr/UgLoEyXAAVLx/E7I7wgsgfYUu0iHVYg=
            =1JyF
            -----END PGP MESSAGE-----
          fp: E60B7B08952B00CAFC82F154F079120C11682A03
        - created_at: "2021-08-10T22:18:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4bZl5U5v+PuAQ//a6sN1CQtGKact4gEXBSuMl7PIAKfd+BVSp0lstun/hy3
            GYOzjCcMhhVxfzPVjWgRFagfWvnWhMsBUhuPu5rCegZXWNQwrTrdfet6y/vS2gqG
            e/9XBgxjejEtyarGDm0gSDNJgBDKdg+rq5RFQEzQnUKKR5R2uheYK5gF+Eagt1IN
            hKTlslnWABlLqp0qje9+pTGwJcPSRDZohnS4tHlTXRyHfsQ7VZ9hwD2Fm+l8lIFg
            H9jRm68iMG2FI4U7EvnUKQ38LPju66GFGpHK/egkRWMLLOogGDV2eXw2x6oxHIkh
            Uci12A5l8g0nMef5tIQfQ2fJ3A8v8ygcDixWTTD50Q8zBaZ0FsjY28DFLnWqBYop
            QRosIeeb8TsAkU1nb1KMSYixFDLZAp97MCmvjg60OaScUCfTJlM/UOj5GmO49z9b
            ey79SJXMBtrE4ZkCNjivg56OkRoDtfETjROhgtVd259aREtpZZpLshgbQl4Fkb3C
            xlgNdmAoPwX8W+WPDNA2R9ACyJC9SHhnQxLtBtiLOv/K1qVyUzWd0zkuTZRVfZPm
            mjti9pgbcsCfB5ufAWHKPDSKoBGAkQsRZgAg9CVb+Pl5BW+TMbh4Ildi43XeWv98
            DPJGhDKcXJELLsu3wLl3MC88Qi4X2Q5y5IMokqzMjFZPGMi+Q/+c+v+aZQ7auHPS
            XgF7CP82ccm6O8+2dJ0xUK+6OW+ccpJbmvCo8dVxldSMGmRXcD4qKzkxATxsD49x
            WB7/bbXXkE0eIMnUEOtE4JiYomLsEzreT8yrqHHkSMei963Co7hrN/LruDmGrR0=
            =049c
            -----END PGP MESSAGE-----
          fp: FA5BAC037E2A4E178724D80AAB1216826FF58B88
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
